### ISSUE TITLE
Add the ability to remove decimals from the textField

### ISSUE THREAD

**Issue by eliasturbay** [taglia3/CircularSlider#1]
Hey @taglia3! Great component! I love it ❤️ 

It would be great if you can expose a configurable property to allow the use of it without the decimals.
Thanks in advance!

**Comment by taglia3** [comment]
Hi @eliasturbay ,
thanks for using my swift control.
Yes, i'll expose a new property for setting the number of decimal characters.
I'll push the update in next days, stay tuned!

Thanks,
Matteo

**Comment by eliasturbay** [comment]
Great! 👍

**Comment by taglia3** [comment]
Hi @eliasturbay,

the version with the property for setting the number of decimal characters is live:
pod 'CircularSlider' ', '~> 1.1.0'

Let me know if this satisfied your necessities.

Thanks,
Matteo

**Comment by eliasturbay** [comment]
Thank you very much @taglia3 !!!

There's one more thing that I need to customise and it's no exposed. It's the line above the textfield. 
Do you think you can the ability to hide that line? Should I create another issue?

Best!

**Comment by taglia3** [comment]
@eliasturbay please open a new issue.
