### ISSUE TITLE
How do I get values?

### ISSUE THREAD

**Issue by phishstang65** [taglia3/CircularSlider#7]
How do I get values from the value range that I defined in interface builder?

I installed CircularSlider from CocoaPods and added it in my main.storyboard, then I set the range from 1 to 1000, but I cannot get the values in the range 1-1000... I always get values in the following delegate functions from -2.X to 1.6... to 3.14....

    func circularSlider(circularSlider: CircularSlider, didBeginEditing textfield: UITextField) {
        
        //print("\(String(describing: textfield.text))")
        
    }
    
    func circularSlider(circularSlider: CircularSlider, didEndEditing textfield: UITextField) {
        
        print("asdf \(String(describing: circularSlider.title))")
        
    }
    
}

// MARK: - CircularSliderDelegate
extension ViewController: CircularSliderDelegate {
    func circularSlider(_ circularSlider: CircularSlider, valueForValue value: Float) -> Float {
        return floorf(value)
    }
}

0.0
-1.64434761728344
...
2.98358034030751
3.07363463664357
-3.07239637497121
...
-2.38914958780664
...
-1.53983277461192
-1.460139105621
-1.40709587429103
...
-1.87021156844839
...
2.73103520554794

**Comment by phishstang65** [comment]
The circular slider shows 1-1000...

**Comment by nfajardo** [comment]
Hi,
i love this control.  For this i added this  method to delegate:
`@objc optional func circularSlider(_ circularSlider: CircularSlider, didEndMoved value: Float)`

and at the end of the method  **handleRotationGesture**
i added this code

```
 if gesture.state == UIGestureRecognizerState.ended{
            delegate?.circularSlider!(self, didEndMoved: valueForAngle)
 }
```
After you end moving the slider, you will get your value.
